[package]
name = "liana"
version = "0.4.0"
authors = ["Antoine Poinsot <darosior@protonmail.com>"]
edition = "2018"
repository = "https://github.com/wizardsardine/liana"
license-file = "LICENCE"
keywords = ["bitcoin", "wallet", "safe", "script", "miniscript", "inheritance", "recovery"]
description = "Liana wallet daemon"
exclude = [".github/", ".cirrus.yml", "tests/",  "test_data/", "contrib/", "pyproject.toml"]

[[bin]]
name = "lianad"
path = "src/bin/daemon.rs"
required-features = ["daemon"]

[[bin]]
name = "liana-cli"
path = "src/bin/cli.rs"
required-features = ["daemon"]

[features]
default = ["daemon"]
daemon = ["libc"]

[dependencies]
# For managing transactions (it re-exports the bitcoin crate)
miniscript = { git = "https://github.com/darosior/rust-miniscript", branch = "multipath_descriptors_on_9.0.1", features = ["serde", "compiler"] }

# Don't reinvent the wheel
dirs = "5.0"

# We use TOML for the config, and JSON for RPC
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
serde_json = { version = "1.0", features = ["raw_value"] }

# Logging stuff
log = "0.4"
fern = "0.6"

# In order to have a backtrace on panic, because the
# stdlib does not have a programmatic interface yet
# to work with our custom panic hook.
backtrace = "0.3"

# Pinned to this version because they broke the MSRV in 0.27...
# FIXME: this is unfortunate, we don't receive the updates (sometimes critical) from SQLite.
rusqlite = { version = "0.26.3", features = ["bundled", "unlock_notify"] }

# To talk to bitcoind
jsonrpc = "0.12"

# Used for daemonization
libc = { version = "0.2", optional = true }

# Used for PSBTs
base64 = "0.13"

# Used for generating mnemonics
getrandom = "0.2"

# Additional entropy for generating mnemonics
[target.'cfg(target_arch = "x86")'.dependencies]
rdrand = "0.8"
[target.'cfg(target_arch = "x86_64")'.dependencies]
rdrand = "0.8"

# Used for the hot signer
bip39 = "2.0"
